export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_FAIL = "POST_USER_FAIL";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";